# Generated by Django 4.2.1 on 2023-05-20 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_socio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_nombre', models.CharField(max_length=100)),
                ('emp_apellido', models.CharField(max_length=50)),
                ('emp_legajo', models.IntegerField()),
                ('emp_activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pres_fecha', models.DateTimeField()),
                ('pres_devolucion', models.DateTimeField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_realizados', to='biblioteca.empleado')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='libros', to='biblioteca.libro')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='biblioteca.socio')),
            ],
        ),
    ]
