# Generated by Django 4.2.1 on 2023-05-20 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_empleado_libro_prestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='lib_activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='lib_autor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='autores', to='biblioteca.autor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='lib_descripcion',
            field=models.CharField(default='Libro_Description', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='lib_isbn',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='lib_titulo',
            field=models.CharField(default='Titulo_description', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='emp_activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='emp_apellido',
            field=models.CharField(max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='emp_legajo',
            field=models.IntegerField(verbose_name='Legajo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='emp_nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='pres_devolucion',
            field=models.DateTimeField(null=True, verbose_name='Fecha de devolución'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='pres_fecha',
            field=models.DateTimeField(verbose_name='Fecha de préstamo'),
        ),
    ]
